CREATE TABLE votecomment (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    username VARCHAR(50) NOT NULL,
    comment VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

